export const services = [
  {
    id: 'equity',
    title: 'Equity Trading',
    description: 'Trade in NSE & BSE listed stocks with expert guidance, real-time data, and advanced order management tools.',
    icon: 'TrendingUp',
    href: '#',
    color: 'from-blue-500 to-blue-700',
    tag: 'NSE · BSE',
  },
  {
    id: 'derivatives',
    title: 'Equity Derivatives',
    description: 'Leverage F&O instruments — futures and options — with sophisticated risk management and strategy support.',
    icon: 'BarChart2',
    href: '#',
    color: 'from-indigo-500 to-indigo-700',
    tag: 'F&O',
  },
  {
    id: 'commodities',
    title: 'Commodities Trading',
    description: 'Trade agricultural and non-agricultural commodities on MCX and NCDEX with real-time price feeds.',
    icon: 'Package',
    href: '#',
    color: 'from-amber-500 to-orange-600',
    tag: 'MCX · NCDEX',
  },
  {
    id: 'currency',
    title: 'Currency Derivatives',
    description: 'Hedge currency risk or speculate on exchange rates with USD, EUR, GBP and JPY currency futures.',
    icon: 'DollarSign',
    href: '#',
    color: 'from-emerald-500 to-teal-600',
    tag: 'Forex',
  },
  {
    id: 'demat',
    title: 'Demat Services',
    description: 'Open and manage your Demat account through CDSL. Seamless settlement, pledging and off-market transfers.',
    icon: 'Wallet',
    href: '#',
    color: 'from-purple-500 to-purple-700',
    tag: 'CDSL DP',
  },
  {
    id: 'ipo',
    title: 'IPO Services',
    description: 'Apply for upcoming IPOs through ASBA. Get research reports and allotment updates on all new public issues.',
    icon: 'Rocket',
    href: '#',
    color: 'from-pink-500 to-rose-600',
    tag: 'ASBA',
  },
  {
    id: 'mf',
    title: 'Mutual Funds',
    description: 'Invest in direct & regular mutual funds via our dedicated MF portal. SIP, lump sum and SWP options available.',
    icon: 'PieChart',
    href: 'https://mutualfunds.myinvestsmart.in/pages/auth/login',
    external: true,
    color: 'from-sky-500 to-blue-600',
    tag: 'AMFI Registered',
  },
]
