export const testimonials = [
  {
    id: 1,
    name: 'Rajesh Sharma',
    designation: 'Business Owner, Indore',
    text: 'InvestSmart has transformed my investment approach. Their expert guidance and personalized advisory helped me grow my portfolio by over 40% in two years. The team is always accessible and deeply knowledgeable.',
    rating: 5,
    avatar: 'RS',
    color: 'from-blue-500 to-blue-700',
  },
  {
    id: 2,
    name: 'Priya Malhotra',
    designation: 'IT Professional, Bhopal',
    text: 'I started my investment journey with InvestSmart 5 years ago. From equity to mutual funds, they have guided me through every market cycle. Their back office platform is seamless and transparent.',
    rating: 5,
    avatar: 'PM',
    color: 'from-purple-500 to-purple-700',
  },
  {
    id: 3,
    name: 'Vikram Patel',
    designation: 'Doctor, Indore',
    text: 'As a busy professional, I needed a trustworthy partner for wealth management. InvestSmart\'s SEBI registration and 15+ years of track record gave me confidence. Their commodity trading desk is excellent.',
    rating: 5,
    avatar: 'VP',
    color: 'from-teal-500 to-emerald-700',
  },
  {
    id: 4,
    name: 'Meena Agarwal',
    designation: 'Retired Teacher, Ujjain',
    text: 'The team at InvestSmart treated me like family. They explained all options patiently and helped me build a safe, diversified portfolio for retirement. I recommend them to all my friends and family.',
    rating: 5,
    avatar: 'MA',
    color: 'from-pink-500 to-rose-700',
  },
  {
    id: 5,
    name: 'Suresh Jain',
    designation: 'Chartered Accountant, Indore',
    text: 'From a professional standpoint, InvestSmart\'s compliance and regulatory standards are impeccable. Their transparent reporting and timely contract notes give complete peace of mind for sophisticated investors.',
    rating: 5,
    avatar: 'SJ',
    color: 'from-amber-500 to-orange-600',
  },
]
